# Generated by Django 6.0.6 on 2026-06-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroConteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_personas', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('captura', models.ImageField(blank=True, null=True, upload_to='capturas/')),
                ('fuente', models.CharField(choices=[('camara', 'Cámara en vivo'), ('imagen', 'Imagen subida')], default='camara', max_length=50)),
            ],
            options={
                'verbose_name': 'Registro de Conteo',
                'verbose_name_plural': 'Registros de Conteo',
                'ordering': ['-timestamp'],
            },
        ),
    ]
